### Amostra de Matrizes

In [1]:
matrizCorreta = [
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78]
 ]

matrizEscadinha = [
 [11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8],
 [8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7],
 [7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6],
 [6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5],
 [5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4],
 [4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3],
 [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
 ]

matrizEscadinhaEstendida = [
 [11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8],
 [8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7],
 [7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6],
 [6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5],
 [5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4],
 [4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3],
 [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8],
 [8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7],
 [7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6],
 [6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4, 5],
 [5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4],
 ]



matrizEscadinhaReversa = [
 [5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2, 3, 4],
 [6, 7, 8, 9, 10, 11, 12, 78,1, 2, 3, 4, 5],
 [7, 8, 9, 10, 11, 12, 78,1, 2, 3, 4, 5, 6],
 [8, 9, 10, 11, 12, 78,1, 2, 3, 4, 5, 6, 7],
 [9, 10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8],
 [10, 11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [11, 12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [12, 78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [78, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78],
 [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1],
 [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 78, 1, 2]
 ]

matrizCorretaANP=[
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634]
]

matrizEscadinhaANP=[
    [17634, 1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500],
    [3500, 17634, 1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400],
    [2400, 3500, 17634, 1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800],
    [800, 2400, 3500, 17634, 1000, 2500, 1200, 3000, 1234, 700, 100, 0],
    [0, 800, 2400, 3500, 17634, 1000, 2500, 1200, 3000, 1234, 700, 100],
    [100, 0, 800, 2400, 3500, 17634, 1000, 2500, 1200, 3000, 1234, 700],
    [700, 100, 0, 800, 2400, 3500, 17634, 1000, 2500, 1200, 3000, 1234],
    [1234, 700, 100, 0, 800, 2400, 3500, 17634, 1000, 2500, 1200, 3000],
    [3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634, 1000, 2500, 1200],
    [1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634, 1000, 2500],
    [1000, 2500, 1200, 3000, 1234, 700, 100, 0, 800, 2400, 3500, 17634]
]

### Importação do Pacote NumPY

In [2]:
import numpy as np

### Criação das Funções

In [3]:
def count_escadinha(matriz, posicao):
    matriz_np = np.matrix(matriz)
    return list(np.diag(matriz_np, k=posicao)).count(matriz_np[0,posicao])

In [4]:
def is_escadinha(m):
    idx = 0
    max_idx = len(m[0])-1
    for i in m[0]:
        if idx != max_idx:
            if count_escadinha(m,idx) > 1:
                pass
                if idx == max_idx -1:
                    print('Matriz Escadinha')
            else:
                if count_escadinha(np.fliplr(m),0) > 1:
                    print('Matriz Invertida')
                    break 
                else:
                    print('Matriz Correta')
                    break
        idx = idx + 1 

In [5]:
def matriz_correta(m):
    matriz_np = np.matrix(m)
    maior=matriz_np[0].max()
    linha= len(matriz_np)
    idx=np.argwhere(matriz_np ==maior)
    resultado=matriz_np[(np.argwhere(idx[:,1] ==linha))]
    for i in m:
        i = resultado
        print(i)

### Validando as Matrizes

In [6]:
is_escadinha(matrizCorreta)

Matriz Correta


In [7]:
is_escadinha(matrizEscadinha)

Matriz Escadinha


In [8]:
is_escadinha(matrizEscadinhaEstendida)

Matriz Escadinha


In [9]:
is_escadinha(matrizEscadinhaReversa)

Matriz Invertida


In [10]:
is_escadinha(matrizCorretaANP)

Matriz Correta


In [11]:
is_escadinha(matrizEscadinhaANP)

Matriz Escadinha


### Retornando a Matriz Correta

In [13]:
matriz_correta(matrizEscadinha)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 78]]]


In [14]:
matriz_correta(matrizEscadinhaANP)

[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
[[[ 1000  2500  1200  3000  1234   700   100     0   800  2400  3500
   17634]]]
